## Importing Libraries

In [1]:
import pandas as pd

In [8]:
# Read the CSV file
data = pd.read_csv("YelloTaxiData.csv")

In [9]:
# Visualising the data
data.head()

,RateCodeID,RatecodeID,VendorID,dropoff_latitude,dropoff_longitude,extra,fare_amount,improvement_surcharge,mta_tax,passenger_count,payment_type,pickup_latitude,pickup_longitude,store_and_fwd_flag,tip_amount,tolls_amount,total_amount,tpep_dropoff_datetime,tpep_pickup_datetime,trip_distance
0,1.0,NaN,1,40.782337,-73.972160,0.0,5.0,0.3,0.5,1,2,40.789295,-73.966629,N,0.0,0.0,5.8,1/9/2015 12:58,1/9/2015 12:54,0.50
1,1.0,NaN,1,40.720489,-73.945465,0.5,12.5,0.3,0.5,1,1,40.723850,-73.992561,N,2.0,0.0,15.8,1/13/2015 23:19,1/13/2015 23:09,3.60
2,1.0,NaN,1,40.721367,-73.994781,0.0,14.5,0.3,0.5,2,2,40.749100,-73.991959,N,0.0,0.0,15.3,1/25/2015 17:37,1/25/2015 17:17,2.30
3,1.0,NaN,1,0.000000,0.000000,1.0,4.0,0.3,0.5,1,1,0.000000,0.000000,N,1.0,0.0,6.8,1/22/2015 19:00,1/22/2015 18:57,0.40
4,1.0,NaN,2,40.737110,-73.998177,0.0,4.5,0.3,0.5,1,1,40.733742,-73.990379,N,1.7,0.0,7.0,1/17/2015 18:16,1/17/2015 18:11,0.48

In [10]:
# Deleting from the 101st row till the last row
data = data.drop(data.index[100:])

In [11]:
data.tail()

,RateCodeID,RatecodeID,VendorID,dropoff_latitude,dropoff_longitude,extra,fare_amount,improvement_surcharge,mta_tax,passenger_count,payment_type,pickup_latitude,pickup_longitude,store_and_fwd_flag,tip_amount,tolls_amount,total_amount,tpep_dropoff_datetime,tpep_pickup_datetime,trip_distance
95,1.0,NaN,2,40.753021,-73.985489,0.0,12.5,0.3,0.5,1,1,40.770061,-73.961319,N,2.50,0.0,15.80,1/7/2015 13:07,1/7/2015 12:48,2.14
96,1.0,NaN,1,40.738331,-73.984406,0.0,9.0,0.0,0.5,2,2,40.765079,-73.974983,N,0.00,0.0,9.80,1/3/2015 12:03,1/3/2015 11:54,2.30
97,1.0,NaN,1,40.714813,-73.991684,0.5,9.0,0.3,0.5,1,1,40.706703,-74.012573,N,2.05,0.0,12.35,1/10/2015 3:35,1/10/2015 3:26,1.90
98,1.0,NaN,2,40.755112,-73.972198,1.0,6.0,0.3,0.5,5,2,40.752449,-73.974998,N,0.00,0.0,7.80,1/21/2015 18:03,1/21/2015 17:56,0.66
99,1.0,NaN,1,40.800392,-73.955452,0.0,21.5,0.0,0.5,1,1,40.729076,-73.984261,N,4.45,0.0,26.75,1/4/2015 19:14,1/4/2015 18:51,6.10

In [13]:
# Saving dataframe to a new csv file
data.to_csv("YelloTaxiData_new.csv", index=False)